# Generated by Django 5.2.4 on 2025-08-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_pelicula_remove_post_categoria_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='plataforma_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace a Plataforma'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(blank=True, help_text='Breve descripción de la película', null=True, verbose_name='Sinopsis'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='categorias',
            field=models.ManyToManyField(related_name='peliculas', to='posts.categoria'),
        ),
    ]
